#集合间的关系
s1={1,2,3,4,5,6,7,8,9,10}
s2={1,2,3,4,5,6}
s3={3,2,1,4,6,5}
print('判断两个集合是否相等')
print(s1==s2)
print(s2==s3)#再次说明集合里的元素是无序的
print('---------')
print('判断一个集合是否是另一个集合的子集')
print(s2.issubset(s1))
print(s3.issubset(s1))
print(s1.issubset(s2))
print('-----------')
print('判断一个集合是否另外一个集合的超集')
print(s1.issuperset(s2))
print(s2.issuperset(s3))
print(s2.issuperset(s1))
print('----------')
print('判断两个集合是否有交集')
print(s1.isdisjoint(s2))#有交集返回false
